Instructions added
zinns/img-descriptions pull request #4
Opened 2023-08-01 18:31 UTC by andysotocruz

2023-08-01 21:26 UTC, andysotocruz commented on README.md
you mean the protection of the global branch of the users right?

2023-08-03 02:53 UTC, eamzea requested changes
- Read two times before pushing your changes.

- What is the objective of adding 2 more images? Those changes are going to be pushed?

2023-08-03 02:53 UTC, eamzea commented on README.md
> +3. Inside the terminal create a branch based on `develop-[name]`.
that's the correct name?

2023-08-03 02:53 UTC, eamzea commented on README.md
> +    > example: `andres/[skylne]` -> `[name]-[imageName]`.
Should be only [name]

2023-08-03 02:53 UTC, eamzea commented on README.md
> +5. Inside the movie skins create a file.
Name folder

2023-08-03 02:53 UTC, eamzea commented on README.md
> +    > example: `andres/skylne/assets/skylne.png` -> `[name]/[image]/assets/[file]` -> `[name]/[image]/assets/[file]`.
When assets folder was created?

2023-08-03 02:53 UTC, eamzea commented on README.md
> +7. Inside the HTML file, make a brief description of what you like most about the [image] .
image*

2023-08-03 02:53 UTC, eamzea commented on README.md
> +
What?
Review orthography and syntax

2023-08-03 02:53 UTC, eamzea commented on README.md
> +3. Dentro de la terminal crear una rama basada en `develop-[nombre]`.
Where is the example?

2023-08-03 02:53 UTC, eamzea commented on README.md
> +    > ejemplo: `andres/[skylne]` -> `[nombre]-[nombreDeLaImagen]`
Same as the English version

2023-08-03 02:53 UTC, eamzea commented on README.md
> +    > ejemplo: `andres/skylne/assets/skylne.png` -> `[nombre]/[imagen]/assets/[archivo]`
Same as English version

2023-08-03 02:53 UTC, eamzea commented on README.md
> +7. Dentro del archivo HTML, realizar una breve descripción de lo que más les agrade de la [imagen] .
Orthography *
image*

2023-08-03 02:53 UTC, eamzea commented on README.md
> +    - Que es lo que menos les agrada de la imagen
Orthography and syntax

2023-08-04 13:14 UTC, closed without merging